### ISSUE TITLE
Refactor stacked bar to use css var

### ISSUE THREAD

**Issue by henryjameslau** [ONSvisual/Simple-charts#13]
Add in css var for the colours so it's easier to change.

e.g.
```
:root{
--bar1:#607D8B;
}

.bar-0{fill:var(--bar1)}
```

**Comment by henryjameslau** [comment]
See https://bl.ocks.org/susielu/23dc3082669ee026c552b85081d90976 for example

**Comment by JureStabuc** [comment]
Also the legend now chooses background colours from the same colour palette in config
