### ISSUE TITLE
Clean up sources and font weights

### ISSUE THREAD

**Issue by henryjameslau** [ONSvisual/Simple-charts#14]
Fonts loaded should be open sans 400 and 700, we don't use 300, 600 or condensed anymore

`<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">`

Source size and weight should match ONS website

**Comment by henryjameslau** [comment]
Sources should be `h6`
```
h6 {
   font-size: 16px;
   margin: 16px 0 8px 0;
   font-weight: 700;
   color:#323132;
}
```

**Comment by JureStabuc** [comment]
All sources updated, links stripped out.
