### ISSUE TITLE
Tweak circles in bump chart?

### ISSUE THREAD

**Issue by jtrim-ons** [ONSvisual/Simple-charts#95]
When you hover on the bump chart, the lines show through the faded circles.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/79704945/149127053-be7cd8dc-69cf-4a79-b5d3-9ff10a43870e.png">

Would it look slightly better like this?

<img width="600" alt="image" src="https://user-images.githubusercontent.com/79704945/149127105-b19885f9-5374-447f-ae86-22a9ea04617e.png">

A quick way to do this is to add the following code just before the circles are created:

```js
        d3.select(".circles").append('g')
          .selectAll('circle')
          .data(lines[names[i]])
          .enter()
          .append('circle')
          .attr('cx',function(d,i){ return x(d.date) })
          .attr('cy',function(d){return y(d.rank)})
          .attr('r',10)
          .style('fill','white');
```

This adds an opaque white circle behind each coloured circle, so that the lines don't show through.

The chart is fine as it is, so maybe this is a pointless issue!

**Comment by Rachel-Price-ONS** [comment]
I don't think it's a pointless issue, the top chart looks a bit sloppy so would be good to fix it

**Comment by jtrim-ons** [comment]
Thanks Rachel.
